#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    a=n-1
    arr = list(map(int, input().rstrip().split()))
    print(' '.join(map(str, reversed(arr))))
        
        
    
